site_name: Zero to Mastery Learn PyTorch for Deep Learning
site_url: https://www.learnpytorch.io
site_description: Learn important machine learning concepts hands-on by writing PyTorch code.

repo_url: https://github.com/mrdbourke/pytorch-deep-learning/
repo_name: mrdbourke/pytorch_deep_learning

theme:
  name: material
  logo: assets/ztm-logo-and-pytorch-logo.png
  favicon: assets/ztm-logo-and-pytorch-logo.png
  features:
    - navigation.instant
    - navigation.top
  palette:
    primary: black

markdown_extensions:
  - meta
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  
plugins:
 - mkdocs-jupyter:
    include_source: True
 - search
 - social

edit_uri: ""

nav:
  - Home: 'index.md'
  - 00. Getting Started with PyTorch: '00_pytorch_fundamentals.ipynb'
  - 01. PyTorch Machine Learning Workflow: '01_pytorch_workflow.ipynb'
  - 02. PyTorch Neural Network Classification: '02_pytorch_classification.ipynb'
  - 03. PyTorch Computer Vision: '03_pytorch_computer_vision.ipynb'
  - 04. PyTorch Custom Datasets: '04_pytorch_custom_datasets.ipynb'
  - 05. PyTorch Going Modular: '05_pytorch_going_modular.md'
  - 06. PyTorch Transfer Learning: '06_pytorch_transfer_learning.ipynb'
  - 07. PyTorch Experiment Tracking: '07_pytorch_experiment_tracking.ipynb'
  - 08. Replicating Machine Learning Research Papers with PyTorch: '08_pytorch_paper_replicating.ipynb'
  - 09. Deploying PyTorch Machine Learning Models: '09_pytorch_model_deployment.ipynb'
  - A Quick PyTorch 2 Tutorial: 'pytorch_2_intro.ipynb'
  - PyTorch Extra Resources: 'pytorch_extra_resources.md'
  - PyTorch Cheatsheet: 'pytorch_cheatsheet.ipynb'
  - Three Most Common PyTorch Errors: 'pytorch_most_common_errors.ipynb'
  # - Test 00 as markdown: '00_pytorch_fundamentals.md'

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/mrdbourke
    - icon: fontawesome/brands/github
      link: https://github.com/mrdbourke/pytorch-deep-learning
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCr8O8l5cCX85Oem1d18EezQ
